### PR TITLE
New options: noDataText, hideFlag, and flagType null option.

### PR DESCRIPTION
**Pull request by codefir**
Added the ability to unset the flagType.

### CODE REVIEW

**Comment by codefir** [comment]
#2nd update:

Added a new option to completely hide the country flag. This is especially useful when the dataset already contains the Country Name (e.g: taken from the database), and it's already localized in the back-end.

**Comment by codefir** [comment]
**3rd update**

Added a new option (called noDataText) to allow for the "No data available" to be changed to w/e string the user wants. Helps with localization.

**Comment by codefir** [comment]
**4th update**

Fixed the example coded block provided in the README file, should also be fixed on your blog exmaple, since that's where the Documentation points to.

**Comment by StephanWagner** [comment]
Thanks @codefir! Nice addition!
Just released version v1.3.0 with these new changes.

**Pull request merged**
